In [0]:
%tensorflow_version 1.x

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
tf.__version__

'1.15.0'

In [3]:
hello = tf.constant('Hello')
world = tf.constant('World')
print(hello, type(hello))

Tensor("Const:0", shape=(), dtype=string) <class 'tensorflow.python.framework.ops.Tensor'>


In [4]:
with tf.Session() as sess:
  result = sess.run(hello+world)
print(result)

b'HelloWorld'


In [5]:
var1 = tf.constant(10)
var2 = tf.constant(20)
with tf.Session() as sess:
  var3 = sess.run(var1+var2)
print(var3)

30


In [6]:
var1 + var2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [7]:
const = tf.constant(20)
mat_1 = tf.fill([5,5],10)
print(mat_1)

Tensor("Fill:0", shape=(5, 5), dtype=int32)


In [0]:
zeros = tf.zeros([5,5])

In [0]:
ones = tf.ones([5,5])

In [0]:
randn = tf.random_normal((4,4), mean = 0, stddev = 1.0)

In [0]:
randu = tf.random_uniform((4,4), minval = 0, maxval = 1)

In [0]:
myops = [const, mat_1, zeros, ones, randn, randu]

In [0]:
sess = tf.InteractiveSession()

In [17]:
for op in myops:
  print(sess.run(op))
  print()

20

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[ 2.0775766  -1.2862666   0.83186466 -0.89025587]
 [ 0.5731487   1.0252265   0.4581761   0.6896663 ]
 [-2.5394514  -2.4209118  -0.06634889  1.302369  ]
 [-1.2847196   1.1038892   0.6719786  -1.0144374 ]]

[[0.69385505 0.5801153  0.10270894 0.551576  ]
 [0.8485668  0.4690025  0.12826455 0.30774736]
 [0.62097895 0.5872792  0.5232383  0.65302885]
 [0.92076766 0.06844234 0.6658827  0.8474488 ]]



In [19]:
for op in myops:
  print(op.eval())
  print()

20

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[ 0.38834506  0.546895   -0.7772938  -0.5529033 ]
 [ 0.16826963  0.8241279   1.8224491  -0.59356785]
 [-0.8103811   2.0822432  -1.0577857   0.2378815 ]
 [ 0.2440202   1.2860861   0.1220637   1.345629  ]]

[[0.23759305 0.7138604  0.3802197  0.21663642]
 [0.59984934 0.9429797  0.18843901 0.9273665 ]
 [0.14438534 0.86500347 0.02605546 0.13808572]
 [0.48048174 0.7993592  0.9495474  0.8389214 ]]



In [0]:
a = tf.constant([[1,2], [3,4]])

In [21]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [22]:
b = tf.constant([[10], [100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [23]:
result = tf.matmul(a,b)
result

<tf.Tensor 'MatMul:0' shape=(2, 1) dtype=int32>

In [24]:
result.eval()

array([[210],
       [430]], dtype=int32)

In [25]:
sess.run(result)

array([[210],
       [430]], dtype=int32)