<a href="https://colab.research.google.com/github/bosecodes/ML-with-Python/blob/master/tf2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 1.x

In [0]:
import tensorflow as tf

In [0]:
var1 = tf.constant(10)
var2 = tf.constant(20)
var3 = var1 + var2

In [29]:
with tf.Session() as sess:
  result = sess.run(var3)
print(result)

30


In [30]:
print(var3)

Tensor("add_3:0", shape=(), dtype=int32)


In [31]:
print(tf.get_default_graph())

In [32]:
g = tf.Graph()
print(g)

In [33]:
g_1 = tf.get_default_graph()
print(g_1)

In [34]:
g_2 = tf.Graph()
print(g_2)

In [35]:
with g_2.as_default():
  print(g_2 is tf.get_default_graph())

True


In [3]:
# TF GRAPHS
%tensorflow_version 1.x
import tensorflow as tf
sess = tf.InteractiveSession()

my_tensor = tf.random_uniform((4,4), 0, 1)
my_tensor

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


<tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>

In [9]:
my_var = tf.Variable(initial_value = my_tensor)
print(my_var)

# we can't run sess.run on my_var here yet since we have to initialise all variables first
#sess.run(my_var)

<tf.Variable 'Variable_2:0' shape=(4, 4) dtype=float32_ref>


In [0]:
# we do that by initialising an object called init, global_variables_initializer()
# and then running it in a session, over here, we are using an interactive session
# so we directly use sess.run on init

init = tf.global_variables_initializer()

In [0]:
sess.run(init)

In [12]:
sess.run(my_var)

array([[0.25687027, 0.9935396 , 0.5483614 , 0.85817647],
       [0.22215748, 0.5992149 , 0.48043382, 0.06804514],
       [0.12578166, 0.09537756, 0.3751502 , 0.91797197],
       [0.10301805, 0.938866  , 0.09847844, 0.41528988]], dtype=float32)

In [0]:
placeholder = tf.placeholder(tf.float32, shape = (None,4), name = None)

In [17]:
sess.run(placeholder)

InvalidArgumentError: ignored

In [0]:
## TF GRAPHS

In [0]:
import numpy as np
import tensorflow as tf

np.random.seed(101)
tf.set_random_seed(101)

In [20]:
rand_a = np.random.uniform(0,100,(5,5))
rand_a

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

In [21]:
rand_b = np.random.uniform(0,100,(5,1))
rand_b

array([[99.43179012],
       [52.06653967],
       [57.87895355],
       [73.48190583],
       [54.19617722]])

In [0]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [0]:
add_op = a + b
mul_op = a * b

In [30]:
with tf.Session() as sess:
  add_result = sess.run(add_op, feed_dict = {a:rand_a, b:rand_b})
  print(add_result)
  print()
  mult_result = sess.run(mul_op, feed_dict = {a:rand_a, b:rand_b})
  print(mult_result)

[[151.07166  156.49855  102.27921  116.58396  167.95949 ]
 [135.45622   82.76316  141.42784  124.22093   71.06043 ]
 [113.30171   93.09215   76.06819  136.43912  154.42728 ]
 [ 96.71727   81.83804  133.83675  146.38118  101.10579 ]
 [122.72681  105.982925  59.044632  67.9831    72.89292 ]]

[[5134.644   5674.25     283.12433 1705.4707  6813.8315 ]
 [4341.8125  1598.267   4652.734   3756.8293   988.94635]
 [3207.8113  2038.1029  1052.7742  4546.9805  5588.1157 ]
 [1707.379    614.02527 4434.989   5356.7773  2029.8555 ]
 [3714.0984  2806.6438   262.76764  747.19855 1013.292  ]]
